# General Data
name: iConomy
main: com.iCo6.iConomy
version: 6.0.10b

# Command Data
commands:
    money:
      aliases: [iConomy, iCo]
      description: 检查当前持有的货币

# Generator Data
generators: [bukget]
categories: [ECON]
description: Simple, easy, and intuitive economy for minecraft.
maintainer: Nijikokun
authors: [Nijikokun, SpaceManiac]
website: http://ico.nexua.org
thread: http://bit.ly/iConomy
location: "http://mirror.nexua.org/iConomy/Latest Build/iConomy.jar"
conflicts: []
required: []
optional: [Permissions]
engine:
    craftbukkit:
        min: 0
        max: 1100
    glowstone:
        min: 1
        max: 100

# SuperPerms data
permissions:
    iConomy.*:
        default: op
        description: 拥有全部权限
        children:
            iConomy.help: true
            iConomy.holdings: true
            iConomy.holdings.others: true
            iConomy.top: true
            iConomy.payment: true
            iConomy.accounts.create: true
            iConomy.accounts.remove: true
            iConomy.accounts.give: true
            iConomy.accounts.take: true
            iConomy.accounts.set: true
            iConomy.accounts.status: true
            iConomy.accounts.status.set: true
            iConomy.accounts.purge: true
            iConomy.accounts.empty: true
    iConomy.accounts.*:
        description: 拥有高等级权限
        children:
            iConomy.accounts.create: true
            iConomy.accounts.remove: true
            iConomy.accounts.give: true
            iConomy.accounts.take: true
            iConomy.accounts.set: true
            iConomy.accounts.status: true
            iConomy.accounts.status.set: true
            iConomy.accounts.purge: true
            iConomy.accounts.empty: true
    iConomy.plus:
        description: 拥有普通之上的权限
        children:
            iConomy.help: true
            iConomy.holdings: true
            iConomy.holdings.others: true
            iConomy.top: true
            iConomy.payment: true
    iConomy.user:
        description: 拥有普通权限
        children:
            iConomy.help: true
            iConomy.holdings: true
            iConomy.payment: true
    iConomy.help:
        description: 让你获得一点帮助
        default: op
        command: "/money help"
    iConomy.holdings:
        description: 检查当前持有的货币
        default: op
        command: "/money"
    iConomy.holdings.others:
        description: 检查别人持有的货币
        default: op
        command: "/money <account-name>"
        examples:
          - "/money Nijikokun"
    iConomy.top:
        description: 查看财富排行
        default: op
        command: "/money top"
    iConomy.payment:
        description: 付给其他人钱
        default: op
        command: "/money pay <account-name> <amount>"
        examples:
          - "/money pay Nijikokun 30"
    iConomy.accounts.create:
        description: 创建一个收款账号
        default: op
        command: "/money create <account-name> [amount]"
        examples:
          - "/money create Nijikokun"
          - "/money create Nijikokun 30"
    iConomy.accounts.remove:
        description: 删除一个收款账号
        default: op
        command: "/money remove <account-name>"
        examples:
          - "/money remove Nijikokun"
    iConomy.accounts.give:
        description: 让特定账号增加一定金钱
        default: op
        command: "/money give <account-name> <amount>"
        examples:
          - "/money give Nijikokun 30"
    iConomy.accounts.take:
        description: 让特定账号减少一定金钱
        default: op
        command: "/money take <account-name> <amount>"
        examples:
          - "/money take Nijikokun 30"
    iConomy.accounts.set:
        description: 设置特定账号的金钱
        default: op
        command: "/money set <account-name> <amount>"
        examples:
          - "/money set Nijikokun 30"
    iConomy.accounts.status:
        description: 查看特定账号的可见状态 (可见, 隐藏, 等)
        default: op
        command: "/money status <account-name>"
        examples:
          - "/money status Nijikokun"
    iConomy.accounts.status.set:
        description: 设置特定账号的可见状态 (可见 (1), 隐藏 (0))
        default: op
        command: "/money status <account-name>"
        examples:
          - "/money status Nijikokun"
    iConomy.accounts.purge:
        description: 清除所有账户
        default: op
        command: "/money purge"
    iConomy.accounts.empty:
        description: 删除所有用户数据
        default: op
        command: "/money empty"